version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: on-failure
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - NODE_ENV=production
      - NPM_CONFIG_LOGLEVEL=error
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - DATABASE_URL
